# Generated by Django 5.2.3 on 2025-07-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablesource',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for this timetable (e.g., department, program, or special notes)', null=True),
        ),
    ]
