# Generated by Django 5.2.3 on 2025-07-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_timetablesource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablesource',
            name='timetable_type',
            field=models.CharField(choices=[('teaching', 'Teaching Schedule'), ('exam', 'Exam Schedule'), ('personal', 'Personal Schedule'), ('event', 'Event Schedule'), ('other', 'Other')], default='teaching', help_text='Type of timetable (teaching, exam, personal, etc.)', max_length=20),
        ),
    ]
