# Generated by Django 5.2.3 on 2025-07-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_timetablesource_timetable_type'),
    ]

    operations = [
    ]
